### PR TITLE
Added native FreeBSD libraries

### PR DESCRIPTION
**Pull request by martenlindblad**
Tested on FreeBSD 12.2-RELEASE.
Can connect using trine server and hive-hadoop2 and do calculations on data on HDFS.

Besides all Java dependencies, requires the installation of snappy and zstd: `pkg install snappy zstd`.

### CODE REVIEW

**Comment by martint** [comment]
@cla-bot check

**Comment by electrum** [comment]
Thanks! Can you provide instructions on how to build these? I hope it’s understandable that all the binaries need to built by a project maintainer.

Do you have any ideas on how to test this in the CI? Do you have any experience with this action? https://github.com/marketplace/actions/freebsd-vm

**Comment by martenlindblad** [comment]
> Thanks! Can you provide instructions on how to build these? I hope it’s understandable that all the binaries need to built by a project maintainer.
> 
> Do you have any ideas on how to test this in the CI? Do you have any experience with this action? https://github.com/marketplace/actions/freebsd-vm

Of course, I'll assemble some notes and investigate the freebsd-vm.

**Comment by electrum** [comment]
Following up on this, we should be able to simply add FreeBSD to the Travis config: https://docs.travis-ci.com/user/reference/freebsd/

FreeBSD is also available on AWS EC2, so I can just fire up an instance and compile them there. If you still have your notes, that would save some time. I don't think I've touched FreeBSD in over 15 years.

**Pull request closed without merging**
